services: docker

addons:
  hosts:
    - agorae.local

language:
- ruby

rvm:
- 2.7

cache:
- bundler

install:
# Install CouchDB
- docker run -d -p 5984:5984 -v "$(pwd)"/.couchdb.ini:/opt/couchdb/etc/local.d/docker.ini --name couchdb1 couchdb:2
# Install Argos
- wget https://github.com/Hypertopic/Argos/archive/v3.zip
- unzip v3.zip
- docker run --rm -v "$(pwd)"/Argos-3/app:/app --link couchdb1:couchdb -e URI=http://couchdb:5984/argos benel/couchapp push .
# Install Agorae
- cp couchdb/agorae.sample.json couchdb/agorae.json
- docker run --rm -v "$(pwd)"/couchdb:/app --link couchdb1:couchdb -e URI=http://couchdb:5984/argos benel/couchapp push .
# Set up a user
- curl -X PUT localhost:5984/_users
- curl -X PUT localhost:5984/_users/org.couchdb.user:alice -H 'Accept:application/json' -H 'Content-Type:application/json' -d '{"name":"alice", "password":"lapinblanc", "roles":[], "type":"user"}'
# Install testing environment
- gem install poltergeist rspec

script: rspec spec/features/*
