#-------------------------------------------------------------------------------
# Agorae V2 Config file 
# ------------------------------------------------------------------------------
# Created:     30/10/2021
# Refer to Agorae Docs for more information
#-------------------------------------------------------------------------------
# Author : Sweave (Badr BENNASRI)
#-------------------------------------------------------------------------------

[website]
title = "Agorae"
secondary_title = "Map21 Project"
color = "soon"

[argos]
url = "http://localhost:5984/argos/_design/argos/_rewrite"
corpus = "Vitraux - Bénel"
order = ""

